// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDONc52zFjWm8MVoGaLuQkXpD9_URiSyds',
    appId: '1:558615938803:web:e47f3bf5094da58292d986',
    messagingSenderId: '558615938803',
    projectId: 'twitterproject-85c12',
    authDomain: 'twitterproject-85c12.firebaseapp.com',
    storageBucket: 'twitterproject-85c12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3nyvNU08OGaKmirPplYX6LtRvZ-iz-xg',
    appId: '1:558615938803:android:bd9fa8cc0d0c9a6e92d986',
    messagingSenderId: '558615938803',
    projectId: 'twitterproject-85c12',
    storageBucket: 'twitterproject-85c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzISBRpjapmBaA65RtUZhR-5YtvnKncKo',
    appId: '1:558615938803:ios:edcadbab1210160092d986',
    messagingSenderId: '558615938803',
    projectId: 'twitterproject-85c12',
    storageBucket: 'twitterproject-85c12.appspot.com',
    iosClientId: '558615938803-b7j2qbk4kvr7l7sltsjqkf538pu3272s.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzISBRpjapmBaA65RtUZhR-5YtvnKncKo',
    appId: '1:558615938803:ios:edcadbab1210160092d986',
    messagingSenderId: '558615938803',
    projectId: 'twitterproject-85c12',
    storageBucket: 'twitterproject-85c12.appspot.com',
    iosClientId: '558615938803-b7j2qbk4kvr7l7sltsjqkf538pu3272s.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterproject',
  );
}
